//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Address
{
	public virtual string Country
	{
		get;
		set;
	}

	public virtual string zipCode
	{
		get;
		set;
	}

	public virtual string State
	{
		get;
		set;
	}

	public virtual string City
	{
		get;
		set;
	}

	public virtual string Address
	{
		get;
		set;
	}

}

