//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class DiscussionGroup
{
	private int ID
	{
		get;
		set;
	}

	private string name
	{
		get;
		set;
	}

	private string description
	{
		get;
		set;
	}

	public virtual IEnumerable<DiscussionTopic> DiscussionTopic
	{
		get;
		set;
	}

	public virtual string getName()
	{
		throw new System.NotImplementedException();
	}

	public virtual int getID()
	{
		throw new System.NotImplementedException();
	}

	public virtual string getDescription()
	{
		throw new System.NotImplementedException();
	}

	public DiscussionGroup(int ID, string description, string name)
	{
	}

}

