//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class DiscussionTopic
{
	private string topicTitle
	{
		get;
		set;
	}

	private string topicText
	{
		get;
		set;
	}

	private date date
	{
		get;
		set;
	}

	public virtual IEnumerable<Reply> Reply
	{
		get;
		set;
	}

	public virtual date getDate()
	{
		throw new System.NotImplementedException();
	}

	public virtual string getTopicText()
	{
		throw new System.NotImplementedException();
	}

	public virtual string getTopicTitle()
	{
		throw new System.NotImplementedException();
	}

	public DiscussionTopic(date date, string topicTitle, string topicText)
	{
	}

}

