//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class GameReview
{
	private bool isPositive
	{
		get;
		set;
	}

	private string review
	{
		get;
		set;
	}

	public virtual GameOfStore GameOfStore
	{
		get;
		set;
	}

	public virtual bool getIsPositive()
	{
		throw new System.NotImplementedException();
	}

	public virtual string getReview()
	{
		throw new System.NotImplementedException();
	}

	public GameReview(bool isPositive,string review)
	{
	}

}

