//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Game
{
	private int GameID
	{
		get;
		set;
	}

	private string name
	{
		get;
		set;
	}

	private string description
	{
		get;
		set;
	}

	private string version
	{
		get;
		set;
	}

	private float fileSize
	{
		get;
		set;
	}

    private string[] achievementsVector
	{
		get;
		set;
	}

	public virtual IEnumerable<CompatibleSystem> CompatibleSystem
	{
		get;
		set;
	}

	public virtual IEnumerable<AdditionalSoftware> AdditionalSoftware
	{
		get;
		set;
	}

	public virtual string GetVersion()
	{
		throw new System.NotImplementedException();
	}

	public virtual int GetAdditionalSoftwareRequired()
	{
		throw new System.NotImplementedException();
	}

	private bool GetGameInformationFromDB()
	{
		throw new System.NotImplementedException();
	}

	public virtual string GetName()
	{
		throw new System.NotImplementedException();
	}

	public virtual float getFileSize()
	{
		throw new System.NotImplementedException();
	}

	public virtual string getDescription()
	{
		throw new System.NotImplementedException();
	}

	public virtual string getAchievement(int which)
	{
		throw new System.NotImplementedException();
	}

}

