//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Order
{
	private int ID
	{
		get;
		set;
	}

	private date expirationDate
	{
		get;
		set;
	}

	private int paymentMethod
	{
		get;
		set;
	}

	private bool isPaid
	{
		get;
		set;
	}

	public virtual date getExpirationDate()
	{
		throw new System.NotImplementedException();
	}

	public virtual int getID()
	{
		throw new System.NotImplementedException();
	}

	public virtual int getPaymentMethod()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool getIsPaid()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool cancelOrder()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool finishOrder(int paymentMethod)
	{
		throw new System.NotImplementedException();
	}

}

