//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Profile
{
	private int ID
	{
		get;
		set;
	}

	private string name
	{
		get;
		set;
	}

	private string pictureAddress
	{
		get;
		set;
	}

	private string profileText
	{
		get;
		set;
	}

	private int status
	{
		get;
		set;
	}

	public virtual GameReview GameReview
	{
		get;
		set;
	}

	public virtual IEnumerable<Reply> Reply
	{
		get;
		set;
	}

	public virtual IEnumerable<DiscussionTopic> DiscussionTopic
	{
		get;
		set;
	}

	public virtual IEnumerable<DiscussionGroup> DiscussionGroup
	{
		get;
		set;
	}

	public virtual bool VerifyUsernameAvailability(string username)
	{
		throw new System.NotImplementedException();
	}

	public virtual Profile[] getFriendList()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool changeStatus(int status)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool deliverRequest(int ID)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool openMessageWindows(int friendID)
	{
		throw new System.NotImplementedException();
	}

	public virtual int getID()
	{
		throw new System.NotImplementedException();
	}

	public virtual string getName()
	{
		throw new System.NotImplementedException();
	}

	public virtual int getNumberOfDiscussionGroups()
	{
		throw new System.NotImplementedException();
	}

	public virtual int getNumberOfFriends()
	{
		throw new System.NotImplementedException();
	}

	public virtual int getNumberOfReviewsMade()
	{
		throw new System.NotImplementedException();
	}

	public virtual string getPictureAddress()
	{
		throw new System.NotImplementedException();
	}

	public virtual string getProfileText()
	{
		throw new System.NotImplementedException();
	}

	public virtual int getStatus()
	{
		throw new System.NotImplementedException();
	}

}

