//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Reply
{
	private string replyTitle
	{
		get;
		set;
	}

	private date date
	{
		get;
		set;
	}

	private string text
	{
		get;
		set;
	}

	public virtual date getDate()
	{
		throw new System.NotImplementedException();
	}

	public virtual string getReplyText()
	{
		throw new System.NotImplementedException();
	}

	public virtual string getText()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Review(date date, string replyTitle, string text)
	{
		throw new System.NotImplementedException();
	}

}

