//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class User
{
	private int ID
	{
		get;
		set;
	}

	private string email
	{
		get;
		set;
	}

	private string userName
	{
		get;
		set;
	}

	private string password
	{
		get;
		set;
	}

	private int privacySettings
	{
		get;
		set;
	}

	private string phoneNumber
	{
		get;
		set;
	}

	private int numberOfGames
	{
		get;
		set;
	}

	public virtual IEnumerable<GameOfLibrary> GameOfLibrary
	{
		get;
		set;
	}

    //public virtual IEnumerable<Address> Address
    //{
    //    get;
    //    set;
    //}

	public virtual ShoppingCart ShoppingCart
	{
		get;
		set;
	}

	public virtual Order Order
	{
		get;
		set;
	}

	public virtual Profile Profile
	{
		get;
		set;
	}

	private bool VerifyUserCredentials(string email, string password)
	{
		throw new System.NotImplementedException();
	}

	public virtual int VerifyUserSoftwares()
	{
		throw new System.NotImplementedException();
	}

    //public User(string name, string password, string phoneNumber, Address address)
    //{
    //}

	public virtual bool SaveToDB()
	{
		throw new System.NotImplementedException();
	}

	public User(string email, string password)
	{
	}

	public virtual bool VerifyConfirmationCode(string code)
	{
		throw new System.NotImplementedException();
	}

	private bool VerifyEmailAvailability(string email)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool AddGameToLibrary(Game game)
	{
		throw new System.NotImplementedException();
	}

	private bool SendConfirmationCode(int code)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool ChangePassword(string old, string neew)
	{
		throw new System.NotImplementedException();
	}

	private bool SendPasswordToken(int token)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool VerifyPasswordToken(int token)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool ChangePrivacySettings(int change)
	{
		throw new System.NotImplementedException();
	}

	public virtual int GetNumberOfGames()
	{
		throw new System.NotImplementedException();
	}

	public virtual int GetPrivacySettings()
	{
		throw new System.NotImplementedException();
	}

    //public virtual bool ChangeAddress(Address newAddress)
    //{
    //    throw new System.NotImplementedException();
    //}

	public virtual int RetrieveGamesFromBD()
	{
		throw new System.NotImplementedException();
	}

}

