//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SteamLibrary
{
    public class GameOfLibrary : Game
    {
        private int ID
        {
            get;
            set;
        }

        private float HoursPlayed
        {
            get;
            set;
        }

        private string installedVersion
        {
            get;
            set;
        }

        private bool isInstalled
        {
            get;
            set;
        }

        private bool[] AchievementsUnlocked
        {
            get;
            set;
        }

        public virtual bool CheckInstallation()
        {
            throw new System.NotImplementedException();
        }

        public virtual bool StartGame()
        {
            throw new System.NotImplementedException();
        }

        public virtual bool InstallGame()
        {
            throw new System.NotImplementedException();
        }

        public virtual bool InstallAdditionalSoftware()
        {
            throw new System.NotImplementedException();
        }

        public virtual int CheckAdditionalSoftware()
        {
            throw new System.NotImplementedException();
        }

        public virtual bool UninstallGame()
        {
            throw new System.NotImplementedException();
        }

        public virtual bool StopGame()
        {
            throw new System.NotImplementedException();
        }

        public virtual bool IsUpToDate()
        {
            throw new System.NotImplementedException();
        }

        public virtual bool UpdateGame()
        {
            throw new System.NotImplementedException();
        }

        public virtual bool SaveGOFToDB()
        {
            throw new System.NotImplementedException();
        }

        public float GetHoursPlayed()
        {
            return this.HoursPlayed;
        }

        public virtual string RetrieveSavedGame()
        {
            throw new System.NotImplementedException();
        }

        public GameOfLibrary(int GameID, float hours, int ID)
        {
            this.gameID = GameID;
            this.HoursPlayed = hours;
            this.ID = ID;
            GetGameInformationFromDB();
        }

    }

}