//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class GameOfStore : Game
{
	private float price
	{
		get;
		set;
	}

	private int unitSold
	{
		get;
		set;
	}

	private int numberOfReviews
	{
		get;
		set;
	}

	private float positiveReviewsPercentagem
	{
		get;
		set;
	}

	public virtual IEnumerable<GameReview> GameReview
	{
		get;
		set;
	}

	private float getPrice()
	{
		throw new System.NotImplementedException();
	}

	private int getUnitSold()
	{
		throw new System.NotImplementedException();
	}

	private int getNumberOfReviews()
	{
		throw new System.NotImplementedException();
	}

	private float getPositiveReviesPercentage()
	{
		throw new System.NotImplementedException();
	}

}

